server:
	docker run -p 6080:80 -p 5900:5900 -v /dev/shm:/dev/shm dorowu/ubuntu-desktop-lxde-vnc

#tutorial: https://github.com/fcwu/docker-ubuntu-vnc-desktop
#access http://cherenkov.dyn.ucr.edu:6080/
