build:
	docker build -t itpp .
run:
	docker run -it --rm itpp
#	docker run -it --rm itpp /bin/bash -c "cd sample && make test"
#	docker run -it --rm -v `pwd`/sample:/root/sample itpp 
tag:
	docker tag itpp itpp:v0.1
